name: jocelynke
favicon: null
layout_spectrum: 0.56818
typography_spectrum: 0.8416628835257143
title: Jocelyn Ke
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdd9'
    - '#292730'
    - '#4f4b55'
    - '#7e645d'
    - '#a7866a'
  brandStrength: 0.9559106952510774
  lightness: 0.7078961099032313
  saturation: 0.9171384032815695
  rhythmicContrast: 0.31858497648499906
purpose: []
